
BOT_TOKEN = "8824619909:AAHUn3g00V3qpkXhMdPkl8oBovKdxpCcxkg

OWNER_NAME = "Olnar Bingo"

COMMISSION_PERCENT = 15

FIREBASE_COLLECTION_USERS = "users"
FIREBASE_COLLECTION_WALLETS = "wallets"
FIREBASE_COLLECTION_GAMES = "games"
FIREBASE_COLLECTION_DEPOSITS = "deposits"
FIREBASE_COLLECTION_WITHDRAWALS = "withdrawals"
